### ISSUE TITLE
Doesn't work with non Ref bucket names

### ISSUE THREAD

**Issue by jsyrjala** [funkybob/serverless-s3-deploy#27]
Using this kind of config
````
custom:
  assets:
    targets:
     - bucket: my-bucket
       files:
        - source: './build/'
          globs: '**'
````
Fails with this error
````
this.resolveBucket(...).then is not a function
````

Probably reason is here. Some of the branches return a plain value, some return Promise.
https://github.com/funkybob/serverless-s3-deploy/blob/master/index.js#L85
